'use client';

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'EN' | 'FR' | 'AR' | 'SP' | 'IT' | 'DE' | 'PT' | 'TR' | 'NL';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LANGUAGES: Language[] = ['EN', 'FR', 'AR', 'SP', 'IT', 'DE', 'PT', 'TR', 'NL'];

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && LANGUAGES.includes(savedLang)) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
    if (lang === 'AR') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations['EN'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

const translations: Record<Language, Record<string, string>> = {
  EN: {
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.gallery': 'Gallery',
    'nav.testimonials': 'Testimonials',
    'nav.book': 'Book Now',
    'hero.subtitle': 'The Art of Wellbeing',
    'hero.title': 'Luxury Hammam & Spa Experience in Marrakech Medina',
    'hero.book': 'Book Your Experience',
    'hero.scroll': 'Scroll',
    'about.subtitle': 'Our Heritage',
    'about.title': 'Authentic Moroccan Rituals & Serene Sanctuary',
    'about.p1': 'At Riad Rafaele et SPA, we preserve the soul of the Marrakech Medina. Our heritage is rooted in the ancestral wisdom of Moroccan wellness, where every treatment is a journey through time and sense.',
    'about.p2': 'From the moment you step through our arched corridors, the scent of orange blossom and the cool touch of hand-polished marble invite you to leave the bustle of the souks behind.',
    'services.title': 'Best Hammam in Marrakech',
    'services.subtitle': 'Curated wellness experiences designed to detoxify the body and soul using the finest local ingredients.',
    'service1.title': 'Traditional Hammam',
    'service1.desc': 'A deep cleansing ritual with black soap, kessa scrub, and ghassoul clay wrap for glowing skin.',
    'service2.title': 'Argan Oil Massage',
    'service2.desc': 'Experience the liquid gold of Morocco with a full-body relaxing massage to soothe tension.',
    'service3.title': 'Couple Experience',
    'service3.desc': 'Share a moment of peace with our side-by-side treatments in a private, lantern-lit suite.',
    'services.explore': 'EXPLORE RITUAL',
    'gallery.subtitle': 'Visual Journey',
    'gallery.title': 'The Sanctuary',
    'gallery.desc': 'Every corner of our Riad is designed to inspire tranquility and capture the architectural beauty of Marrakech.',
    'feat1.title': 'Pure Luxury',
    'feat1.desc': 'Refined spaces designed for the most discerning travelers seeking exclusivity.',
    'feat2.title': 'Expert Therapists',
    'feat2.desc': 'Highly trained professionals mastering both modern and ancient wellness techniques.',
    'feat3.title': 'Rich Traditions',
    'feat3.desc': 'Authentic rituals using organic Moroccan ingredients like Ghassoul and Argan.',
    'feat4.title': 'Prime Location',
    'feat4.desc': 'An oasis of calm situated perfectly in the heart of the historic Medina.',
    'test.subtitle': 'Traveler Voices',
    'test.quote': '"The most beautiful Hammam I have ever experienced. The staff at Riad Rafaele made us feel like royalty."',
    'test.author': '— Sarah J., London',
    'book.title': 'Begin Your Journey',
    'book.desc': 'Select your preferred ritual and time. Our concierge will contact you shortly to confirm your reservation and assist with any special requests.',
    'book.form.name': 'Full Name',
    'book.form.email': 'Email Address',
    'book.form.treatment': 'Select Treatment',
    'book.form.t1': 'Traditional Hammam (45 min)',
    'book.form.t2': 'Argan Oil Massage (60 min)',
    'book.form.t3': 'Couple Spa Ritual (90 min)',
    'book.form.t4': 'Full Day Sanctuary Pass',
    'book.form.submit': 'Send Booking Request',
    'book.form.or': 'Or book instantly via',
    'footer.desc': 'A luxurious wellness haven in the heart of Marrakech, offering authentic Moroccan Hammam and Spa rituals.',
    'footer.nav': 'Navigation',
    'footer.info': 'Information',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.guide': 'Local Guide',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.desc': 'Join our community for wellness tips and exclusive offers.',
    'footer.rights': '© 2024 Riad Rafaele et SPA Marrakech. All rights reserved.'
  },
  FR: {
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.gallery': 'Galerie',
    'nav.testimonials': 'Témoignages',
    'nav.book': 'Réserver',
    'hero.subtitle': 'L\'art du Bien-être',
    'hero.title': 'Expérience Spa et Hammam de Luxe dans la Médina de Marrakech',
    'hero.book': 'Réservez votre Expérience',
    'hero.scroll': 'Défiler',
    'about.subtitle': 'Notre Héritage',
    'about.title': 'Rituels Marocains Authentiques & Sanctuaire Serein',
    'about.p1': 'Au Riad Rafaele et SPA, nous préservons l\'âme de la Médina de Marrakech. Notre héritage est ancré dans la sagesse ancestrale du bien-être marocain, où chaque traitement est un voyage à travers le temps et les sens.',
    'about.p2': 'Dès que vous franchissez nos couloirs voûtés, le parfum de la fleur d\'oranger et le toucher frais du marbre poli à la main vous invitent à laisser l\'agitation des souks derrière vous.',
    'services.title': 'Le meilleur Hammam de Marrakech',
    'services.subtitle': 'Des expériences de bien-être conçues pour détoxifier le corps et l\'esprit en utilisant les meilleurs ingrédients locaux.',
    'service1.title': 'Hammam Traditionnel',
    'service1.desc': 'Un rituel de purification en profondeur avec savon noir, gommage kessa et enveloppement au ghassoul pour une peau éclatante.',
    'service2.title': 'Massage à l\'huile d\'Argan',
    'service2.desc': 'Découvrez l\'or liquide du Maroc avec un massage relaxant de tout le corps pour apaiser les tensions.',
    'service3.title': 'Expérience en Couple',
    'service3.desc': 'Partagez un moment de paix avec nos soins côte à côte dans une suite privée éclairée aux lanternes.',
    'services.explore': 'EXPLORER LE RITUEL',
    'gallery.subtitle': 'Voyage Visuel',
    'gallery.title': 'Le Sanctuaire',
    'gallery.desc': 'Chaque recoin de notre Riad est conçu pour inspirer la tranquillité et capturer la beauté architecturale de Marrakech.',
    'feat1.title': 'Luxe Pur',
    'feat1.desc': 'Des espaces raffinés conçus pour les voyageurs les plus exigeants en quête d\'exclusivité.',
    'feat2.title': 'Thérapeutes Experts',
    'feat2.desc': 'Des professionnels hautement qualifiés maîtrisant les techniques de bien-être modernes et anciennes.',
    'feat3.title': 'Riches Traditions',
    'feat3.desc': 'Rituels authentiques utilisant des ingrédients marocains biologiques comme le Ghassoul et l\'Argan.',
    'feat4.title': 'Emplacement de Choix',
    'feat4.desc': 'Un oasis de calme idéalement situé au cœur de la Médina historique.',
    'test.subtitle': 'Voix des Voyageurs',
    'test.quote': '"Le plus beau Hammam que j\'aie jamais expérimenté. Le personnel du Riad Rafaele nous a traités comme des rois."',
    'test.author': '— Sarah J., Londres',
    'book.title': 'Commencez votre Voyage',
    'book.desc': 'Sélectionnez votre rituel et votre heure préférés. Notre concierge vous contactera sous peu pour confirmer votre réservation.',
    'book.form.name': 'Nom Complet',
    'book.form.email': 'Adresse E-mail',
    'book.form.treatment': 'Sélectionner un Traitement',
    'book.form.t1': 'Hammam Traditionnel (45 min)',
    'book.form.t2': 'Massage à l\'huile d\'Argan (60 min)',
    'book.form.t3': 'Rituel Spa en Couple (90 min)',
    'book.form.t4': 'Pass Sanctuaire Journée Complète',
    'book.form.submit': 'Envoyer la Demande',
    'book.form.or': 'Ou réservez instantanément via',
    'footer.desc': 'Un havre de bien-être luxueux au cœur de Marrakech, offrant des rituels authentiques.',
    'footer.nav': 'Navigation',
    'footer.info': 'Informations',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.guide': 'Guide Local',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.desc': 'Rejoignez notre communauté pour des conseils bien-être et des offres exclusives.',
    'footer.rights': '© 2024 Riad Rafaele et SPA Marrakech. Tous droits réservés.'
  },
  AR: {
    'nav.about': 'معلومات عنا',
    'nav.services': 'خدماتنا',
    'nav.gallery': 'الصور',
    'nav.testimonials': 'الآراء',
    'nav.book': 'احجز الآن',
    'hero.subtitle': 'فن الرفاهية',
    'hero.title': 'تجربة حمام وسبا فاخرة في مدينة مراكش القديمة',
    'hero.book': 'احجز تجربتك',
    'hero.scroll': 'تمرير',
    'about.subtitle': 'تراثنا',
    'about.title': 'طقوس مغربية أصيلة وملاذ هادئ',
    'about.p1': 'في رياض رافاييل وسبا، نحافظ على روح مدينة مراكش. تراثنا متجذر في حكمة الأجداد للرفاهية المغربية، حيث يكون كل علاج رحلة عبر الزمن والحواس.',
    'about.p2': 'منذ اللحظة التي تخطو فيها عبر ممراتنا المقوسة، تدعوك رائحة زهر البرتقال واللمسة الباردة للرخام المصقول يدويًا لترك صخب الأسواق وراءك.',
    'services.title': 'أفضل حمام في مراكش',
    'services.subtitle': 'تجارب رفاهية مصممة لتنظيف الجسم والروح باستخدام أجود المكونات المحلية.',
    'service1.title': 'حمام تقليدي',
    'service1.desc': 'طقوس تنظيف عميقة بالصابون الأسود والجلة وتغليف الطين للحصول على بشرة متوهجة.',
    'service2.title': 'مساج بزيت الأركان',
    'service2.desc': 'جرب الذهب السائل للمغرب مع مساج مريح للجسم بالكامل لتهدئة التوتر.',
    'service3.title': 'تجربة الأزواج',
    'service3.desc': 'شارك لحظة من السلام مع علاجاتنا جنبًا إلى جنب في جناح خاص ومضاء بالفوانيس.',
    'services.explore': 'اكتشف الطقوس',
    'gallery.subtitle': 'رحلة بصرية',
    'gallery.title': 'الملاذ',
    'gallery.desc': 'تم تصميم كل زاوية من رياضنا لإلهام الهدوء والتقاط الجمال المعماري لمراكش.',
    'feat1.title': 'رفاهية خالصة',
    'feat1.desc': 'مساحات راقية مصممة للمسافرين الأكثر تميزًا الذين يبحثون عن الحصرية.',
    'feat2.title': 'معالجون خبراء',
    'feat2.desc': 'محترفون مدربون تدريباً عالياً يتقنون تقنيات الرفاهية الحديثة والقديمة.',
    'feat3.title': 'تقاليد غنية',
    'feat3.desc': 'طقوس أصيلة تستخدم مكونات مغربية عضوية مثل الغاسول والأركان.',
    'feat4.title': 'موقع متميز',
    'feat4.desc': 'واحة من الهدوء تقع بشكل مثالي في قلب المدينة التاريخية.',
    'test.subtitle': 'أصوات المسافرين',
    'test.quote': '"أجمل حمام جربته في حياتي. جعلنا الموظفون في رياض رافاييل نشعر وكأننا ملوك."',
    'test.author': '— سارة ج.، لندن',
    'book.title': 'ابدأ رحلتك',
    'book.desc': 'حدد طقوسك المفضلة والوقت المناسب. سيتصل بك الكونسيرج قريبًا لتأكيد حجزك.',
    'book.form.name': 'الاسم الكامل',
    'book.form.email': 'البريد الإلكتروني',
    'book.form.treatment': 'اختر العلاج',
    'book.form.t1': 'حمام تقليدي (45 دقيقة)',
    'book.form.t2': 'مساج بزيت الأركان (60 دقيقة)',
    'book.form.t3': 'طقوس سبا للأزواج (90 دقيقة)',
    'book.form.t4': 'بطاقة الملاذ ليوم كامل',
    'book.form.submit': 'إرسال طلب الحجز',
    'book.form.or': 'أو احجز فوراً عبر',
    'footer.desc': 'ملاذ رفاهية فاخر في قلب مراكش، يقدم طقوس الحمام والسبا المغربية الأصيلة.',
    'footer.nav': 'تنقل',
    'footer.info': 'معلومات',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.guide': 'مرشد محلي',
    'footer.newsletter': 'النشرة الإخبارية',
    'footer.newsletter.desc': 'انضم إلى مجتمعنا للحصول على نصائح حول الرفاهية وعروض حصرية.',
    'footer.rights': '© 2024 رياض رافاييل وسبا مراكش. جميع الحقوق محفوظة.'
  },
  SP: {
    'nav.about': 'Nosotros',
    'nav.services': 'Servicios',
    'nav.gallery': 'Galería',
    'nav.testimonials': 'Opiniones',
    'nav.book': 'Reservar',
    'hero.subtitle': 'El Arte del Bienestar',
    'hero.title': 'Experiencia de Hammam y Spa de Lujo en la Medina de Marrakech',
    'hero.book': 'Reserva tu Experiencia',
    'hero.scroll': 'Desplazarse',
    'about.subtitle': 'Nuestra Herencia',
    'about.title': 'Auténticos Rituales Marroquíes y Santuario Sereno',
    'about.p1': 'En Riad Rafaele et SPA, preservamos el alma de la Medina de Marrakech. Nuestra herencia está arraigada en la sabiduría ancestral del bienestar marroquí, donde cada tratamiento es un viaje a través del tiempo y los sentidos.',
    'about.p2': 'Desde el momento en que atraviesas nuestros pasillos arqueados, el aroma a flor de naranjo y el toque fresco del mármol pulido a mano te invitan a dejar atrás el bullicio de los zocos.',
    'services.title': 'El Mejor Hammam de Marrakech',
    'services.subtitle': 'Experiencias de bienestar diseñadas para desintoxicar el cuerpo y el alma utilizando los mejores ingredientes locales.',
    'service1.title': 'Hammam Tradicional',
    'service1.desc': 'Un ritual de limpieza profunda con jabón negro, exfoliante kessa y envoltura de arcilla ghassoul para una piel radiante.',
    'service2.title': 'Masaje con Aceite de Argán',
    'service2.desc': 'Experimenta el oro líquido de Marruecos con un masaje relajante de cuerpo completo para aliviar la tensión.',
    'service3.title': 'Experiencia en Pareja',
    'service3.desc': 'Comparte un momento de paz con nuestros tratamientos lado a lado en una suite privada iluminada con linternas.',
    'services.explore': 'EXPLORAR RITUAL',
    'gallery.subtitle': 'Viaje Visual',
    'gallery.title': 'El Santuario',
    'gallery.desc': 'Cada rincón de nuestro Riad está diseñado para inspirar tranquilidad y capturar la belleza arquitectónica de Marrakech.',
    'feat1.title': 'Puro Lujo',
    'feat1.desc': 'Espacios refinados diseñados para los viajeros más exigentes que buscan exclusividad.',
    'feat2.title': 'Terapeutas Expertos',
    'feat2.desc': 'Profesionales altamente capacitados que dominan técnicas de bienestar modernas y antiguas.',
    'feat3.title': 'Ricas Tradiciones',
    'feat3.desc': 'Rituales auténticos utilizando ingredientes marroquíes orgánicos como Ghassoul y Argán.',
    'feat4.title': 'Ubicación Privilegiada',
    'feat4.desc': 'Un oasis de calma situado perfectamente en el corazón de la histórica Medina.',
    'test.subtitle': 'Voces de Viajeros',
    'test.quote': '"El Hammam más hermoso que he experimentado. El personal de Riad Rafaele nos hizo sentir como realeza."',
    'test.author': '— Sarah J., Londres',
    'book.title': 'Comienza tu Viaje',
    'book.desc': 'Selecciona tu ritual preferido y la hora. Nuestro conserje se comunicará contigo pronto para confirmar tu reserva.',
    'book.form.name': 'Nombre Completo',
    'book.form.email': 'Correo Electrónico',
    'book.form.treatment': 'Seleccionar Tratamiento',
    'book.form.t1': 'Hammam Tradicional (45 min)',
    'book.form.t2': 'Masaje con Aceite de Argán (60 min)',
    'book.form.t3': 'Ritual de Spa en Pareja (90 min)',
    'book.form.t4': 'Pase de Santuario Día Completo',
    'book.form.submit': 'Enviar Solicitud de Reserva',
    'book.form.or': 'O reserva al instante vía',
    'footer.desc': 'Un lujoso refugio de bienestar en el corazón de Marrakech, ofreciendo auténticos rituales de Hammam y Spa.',
    'footer.nav': 'Navegación',
    'footer.info': 'Información',
    'footer.privacy': 'Política de Privacidad',
    'footer.terms': 'Términos de Servicio',
    'footer.guide': 'Guía Local',
    'footer.newsletter': 'Boletín',
    'footer.newsletter.desc': 'Únete a nuestra comunidad para obtener consejos de bienestar y ofertas exclusivas.',
    'footer.rights': '© 2024 Riad Rafaele et SPA Marrakech. Todos los derechos reservados.'
  },
  IT: {
    'nav.about': 'Chi Siamo',
    'nav.services': 'Servizi',
    'nav.gallery': 'Galleria',
    'nav.testimonials': 'Testimonianze',
    'nav.book': 'Prenota Ora',
    'hero.subtitle': 'L\'Arte del Benessere',
    'hero.title': 'Esperienza Lussuosa di Hammam & Spa nella Medina di Marrakech',
    'hero.book': 'Prenota la Tua Esperienza',
    'hero.scroll': 'Scorri',
    'about.subtitle': 'La Nostra Eredità',
    'about.title': 'Autentici Rituali Marocchini e Santuario Sereno',
    'about.p1': 'Al Riad Rafaele et SPA, preserviamo l\'anima della Medina di Marrakech. La nostra eredità affonda le radici nell\'antica saggezza del benessere marocchino, dove ogni trattamento è un viaggio.',
    'about.p2': 'Nel momento in cui si attraversano i nostri corridoi ad arco, il profumo di fiori d\'arancio ti invita a lasciarti alle spalle il caos dei souk.',
    'services.title': 'Il Miglior Hammam a Marrakech',
    'services.subtitle': 'Esperienze di benessere curate per disintossicare il corpo e l\'anima.',
    'service1.title': 'Hammam Tradizionale',
    'service1.desc': 'Un rituale di pulizia profonda con sapone nero, scrub kessa e argilla ghassoul.',
    'service2.title': 'Massaggio con Olio di Argan',
    'service2.desc': 'Vivi l\'oro liquido del Marocco con un massaggio rilassante su tutto il corpo.',
    'service3.title': 'Esperienza di Coppia',
    'service3.desc': 'Condividi un momento di pace con i nostri trattamenti fianco a fianco in una suite privata.',
    'services.explore': 'ESPLORA IL RITUALE',
    'gallery.subtitle': 'Viaggio Visivo',
    'gallery.title': 'Il Santuario',
    'gallery.desc': 'Ogni angolo del nostro Riad è progettato per ispirare tranquillità.',
    'feat1.title': 'Puro Lusso',
    'feat1.desc': 'Spazi raffinati progettati per i viaggiatori più esigenti.',
    'feat2.title': 'Terapisti Esperti',
    'feat2.desc': 'Professionisti altamente qualificati che padroneggiano tecniche moderne e antiche.',
    'feat3.title': 'Ricche Tradizioni',
    'feat3.desc': 'Rituali autentici che utilizzano ingredienti biologici marocchini.',
    'feat4.title': 'Posizione Ideale',
    'feat4.desc': 'Un\'oasi di calma situata perfettamente nel cuore della storica Medina.',
    'test.subtitle': 'Voci dei Viaggiatori',
    'test.quote': '"L\'Hammam più bello in cui sia mai stato. Ci siamo sentiti dei reali."',
    'test.author': '— Sarah J., Londra',
    'book.title': 'Inizia il Tuo Viaggio',
    'book.desc': 'Seleziona il rituale e l\'orario. Il nostro concierge ti contatterà a breve.',
    'book.form.name': 'Nome Completo',
    'book.form.email': 'Indirizzo Email',
    'book.form.treatment': 'Seleziona Trattamento',
    'book.form.t1': 'Hammam Tradizionale (45 min)',
    'book.form.t2': 'Massaggio con Olio di Argan (60 min)',
    'book.form.t3': 'Rituale Spa di Coppia (90 min)',
    'book.form.t4': 'Pass Santuario Intera Giornata',
    'book.form.submit': 'Invia Richiesta di Prenotazione',
    'book.form.or': 'O prenota immediatamente tramite',
    'footer.desc': 'Un lussuoso rifugio di benessere nel cuore di Marrakech.',
    'footer.nav': 'Navigazione',
    'footer.info': 'Informazioni',
    'footer.privacy': 'Informativa sulla Privacy',
    'footer.terms': 'Termini di Servizio',
    'footer.guide': 'Guida Locale',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.desc': 'Unisciti alla nostra community per consigli sul benessere.',
    'footer.rights': '© 2024 Riad Rafaele et SPA Marrakech. Tutti i diritti riservati.'
  },
  DE: {
    'nav.about': 'Über Uns',
    'nav.services': 'Leistungen',
    'nav.gallery': 'Galerie',
    'nav.testimonials': 'Erfahrungen',
    'nav.book': 'Buchen',
    'hero.subtitle': 'Die Kunst des Wohlbefindens',
    'hero.title': 'Luxus Hammam & Spa Erlebnis in der Medina von Marrakesch',
    'hero.book': 'Erlebnis Buchen',
    'hero.scroll': 'Scrollen',
    'about.subtitle': 'Unser Erbe',
    'about.title': 'Authentische marokkanische Rituale & ruhiges Heiligtum',
    'about.p1': 'Im Riad Rafaele et SPA bewahren wir die Seele der Medina von Marrakesch. Unser Erbe wurzelt in der uralten Weisheit des marokkanischen Wohlbefindens.',
    'about.p2': 'Sobald Sie unsere gewölbten Gänge betreten, laden Sie der Duft von Orangenblüten und die Kühle des handpolierten Marmors ein, den Trubel der Souks hinter sich zu lassen.',
    'services.title': 'Bestes Hammam in Marrakesch',
    'services.subtitle': 'Ausgewählte Wellness-Erlebnisse zur Entgiftung von Körper und Seele.',
    'service1.title': 'Traditionelles Hammam',
    'service1.desc': 'Ein tiefenreinigendes Ritual mit schwarzer Seife, Kessa-Peeling und Ghassoul-Tonerde.',
    'service2.title': 'Arganöl-Massage',
    'service2.desc': 'Erleben Sie das flüssige Gold Marokkos mit einer entspannenden Ganzkörpermassage.',
    'service3.title': 'Pärchen-Erlebnis',
    'service3.desc': 'Teilen Sie einen Moment der Ruhe mit unseren Behandlungen nebeneinander in einer privaten Suite.',
    'services.explore': 'RITUAL ENTDECKEN',
    'gallery.subtitle': 'Visuelle Reise',
    'gallery.title': 'Das Heiligtum',
    'gallery.desc': 'Jede Ecke unseres Riads ist so gestaltet, dass sie zur Ruhe inspiriert.',
    'feat1.title': 'Purer Luxus',
    'feat1.desc': 'Raffinierte Räume für die anspruchsvollsten Reisenden.',
    'feat2.title': 'Erfahrene Therapeuten',
    'feat2.desc': 'Hochqualifizierte Fachleute, die moderne und alte Techniken beherrschen.',
    'feat3.title': 'Reiche Traditionen',
    'feat3.desc': 'Authentische Rituale mit biologischen marokkanischen Zutaten.',
    'feat4.title': 'Beste Lage',
    'feat4.desc': 'Eine Oase der Ruhe, perfekt gelegen im Herzen der historischen Medina.',
    'test.subtitle': 'Stimmen der Reisenden',
    'test.quote': '"Das schönste Hammam, das ich je erlebt habe. Das Personal war königlich."',
    'test.author': '— Sarah J., London',
    'book.title': 'Beginnen Sie Ihre Reise',
    'book.desc': 'Wählen Sie Ihr gewünschtes Ritual. Unser Concierge wird sich in Kürze mit Ihnen in Verbindung setzen.',
    'book.form.name': 'Vollständiger Name',
    'book.form.email': 'E-Mail Adresse',
    'book.form.treatment': 'Behandlung Wählen',
    'book.form.t1': 'Traditionelles Hammam (45 Min)',
    'book.form.t2': 'Arganöl-Massage (60 Min)',
    'book.form.t3': 'Pärchen Spa-Ritual (90 Min)',
    'book.form.t4': 'Tageskarte Heiligtum',
    'book.form.submit': 'Buchungsanfrage Senden',
    'book.form.or': 'Oder buchen Sie sofort über',
    'footer.desc': 'Eine luxuriöse Wellness-Oase im Herzen von Marrakesch.',
    'footer.nav': 'Navigation',
    'footer.info': 'Informationen',
    'footer.privacy': 'Datenschutzrichtlinie',
    'footer.terms': 'Nutzungsbedingungen',
    'footer.guide': 'Lokaler Führer',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter.desc': 'Treten Sie unserer Community bei für Wellness-Tipps.',
    'footer.rights': '© 2024 Riad Rafaele et SPA Marrakesch. Alle Rechte vorbehalten.'
  },
  PT: {
    'nav.about': 'Sobre',
    'nav.services': 'Serviços',
    'nav.gallery': 'Galeria',
    'nav.testimonials': 'Testemunhos',
    'nav.book': 'Reservar',
    'hero.subtitle': 'A Arte do Bem-Estar',
    'hero.title': 'Experiência de Hammam e Spa de Luxo na Medina de Marraquexe',
    'hero.book': 'Reserve a sua Experiência',
    'hero.scroll': 'Deslizar',
    'about.subtitle': 'A Nossa Herança',
    'about.title': 'Autênticos Rituais Marroquinos e Santuário Sereno',
    'about.p1': 'No Riad Rafaele et SPA, preservamos a alma da Medina de Marraquexe.',
    'about.p2': 'A partir do momento em que entra, o aroma da flor de laranjeira convida-o a deixar a agitação para trás.',
    'services.title': 'O Melhor Hammam em Marraquexe',
    'services.subtitle': 'Experiências de bem-estar selecionadas para desintoxicar o corpo.',
    'service1.title': 'Hammam Tradicional',
    'service1.desc': 'Um ritual de limpeza profunda com sabão negro, esfoliação kessa e ghassoul.',
    'service2.title': 'Massagem com Óleo de Argão',
    'service2.desc': 'Experimente o ouro líquido de Marrocos com uma massagem relaxante.',
    'service3.title': 'Experiência para Casais',
    'service3.desc': 'Partilhe um momento de paz com os nossos tratamentos lado a lado.',
    'services.explore': 'EXPLORAR RITUAL',
    'gallery.subtitle': 'Viagem Visual',
    'gallery.title': 'O Santuario',
    'gallery.desc': 'Cada canto do nosso Riad foi concebido para inspirar tranquilidade.',
    'feat1.title': 'Puro Luxo',
    'feat1.desc': 'Espaços requintados concebidos para os viajantes mais exigentes.',
    'feat2.title': 'Terapeutas Especialistas',
    'feat2.desc': 'Profissionais altamente formados que dominam técnicas modernas e antigas.',
    'feat3.title': 'Ricas Tradições',
    'feat3.desc': 'Rituais autênticos usando ingredientes orgânicos marroquinos.',
    'feat4.title': 'Localização Privilegiada',
    'feat4.desc': 'Um oásis de calma situado perfeitamente no coração da Medina.',
    'test.subtitle': 'Vozes de Viajantes',
    'test.quote': '"O Hammam mais bonito que já experimentei. A equipa foi fantástica."',
    'test.author': '— Sarah J., Londres',
    'book.title': 'Comece a sua Viagem',
    'book.desc': 'Selecione o seu ritual preferido. O nosso concierge contactá-lo-á em breve.',
    'book.form.name': 'Nome Completo',
    'book.form.email': 'Endereço de Email',
    'book.form.treatment': 'Selecionar Tratamento',
    'book.form.t1': 'Hammam Tradicional (45 min)',
    'book.form.t2': 'Massagem com Óleo de Argão (60 min)',
    'book.form.t3': 'Ritual Spa para Casais (90 min)',
    'book.form.t4': 'Passe Diário para o Santuário',
    'book.form.submit': 'Enviar Pedido de Reserva',
    'book.form.or': 'Ou reserve instantaneamente via',
    'footer.desc': 'Um luxuoso refúgio de bem-estar no coração de Marraquexe.',
    'footer.nav': 'Navegação',
    'footer.info': 'Informações',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos de Serviço',
    'footer.guide': 'Guia Local',
    'footer.newsletter': 'Boletim Informativo',
    'footer.newsletter.desc': 'Junte-se à nossa comunidade para dicas de bem-estar.',
    'footer.rights': '© 2024 Riad Rafaele et SPA Marrakech. Todos os direitos reservados.'
  },
  TR: {
    'nav.about': 'Hakkımızda',
    'nav.services': 'Hizmetler',
    'nav.gallery': 'Galeri',
    'nav.testimonials': 'Görüşler',
    'nav.book': 'Rehber',
    'hero.subtitle': 'Sağlık Sanatı',
    'hero.title': 'Marakeş Medinesi\'nde Lüks Hamam ve Spa Deneyimi',
    'hero.book': 'Deneyiminizi Ayırtın',
    'hero.scroll': 'Kaydır',
    'about.subtitle': 'Mirasımız',
    'about.title': 'Otantik Fas Ritüelleri ve Sakin Sığınak',
    'about.p1': 'Riad Rafaele et SPA\'da Marakeş Medinesi\'nin ruhunu koruyoruz.',
    'about.p2': 'Kemerli koridorlarımızdan adım attığınız anda, rahatlamaya davetlisiniz.',
    'services.title': 'Marakeş\'teki En İyi Hamam',
    'services.subtitle': 'Vücudu ve ruhu arındırmak için tasarlanmış özel sağlıklı yaşam deneyimleri.',
    'service1.title': 'Geleneksel Hamam',
    'service1.desc': 'Siyah sabun, kesse peelingi ve ghassoul kili ile derinlemesine temizlik ritüeli.',
    'service2.title': 'Argan Yağı Masajı',
    'service2.desc': 'Rahatlatıcı tüm vücut masajı ile Fas\'ın sıvı altınını deneyimleyin.',
    'service3.title': 'Çifte Özel Deneyim',
    'service3.desc': 'Özel, fenerle aydınlatılmış süitimizde yan yana tedavilerle huzuru paylaşın.',
    'services.explore': 'RİTÜELİ KEŞFET',
    'gallery.subtitle': 'Görsel Yolculuk',
    'gallery.title': 'Sığınak',
    'gallery.desc': 'Riad\'ımızın her köşesi huzur ilham etmek için tasarlanmıştır.',
    'feat1.title': 'Saf Lüks',
    'feat1.desc': 'Ayrıcalık arayan en seçici gezginler için tasarlanmış alanlar.',
    'feat2.title': 'Uzman Terapistler',
    'feat2.desc': 'Modern ve antik tekniklere hakim yüksek eğitimli profesyoneller.',
    'feat3.title': 'Zengin Gelenekler',
    'feat3.desc': 'Organik Fas malzemeleri kullanılan otantik ritüeller.',
    'feat4.title': 'Harika Konum',
    'feat4.desc': 'Tarihi Medine\'nin kalbinde mükemmel bir şekilde yer alan sakin bir vaha.',
    'test.subtitle': 'Gezgin Sesleri',
    'test.quote': '"Şimdiye kadar yaşadığım en güzel hamam deneyimi."',
    'test.author': '— Sarah J., Londra',
    'book.title': 'Yolculuğunuza Başlayın',
    'book.desc': 'Tercih ettiğiniz ritüeli ve saati seçin. Görevlimiz rezervasyonunuzu onaylamak için iletişime geçecektir.',
    'book.form.name': 'Tam Adınız',
    'book.form.email': 'E-posta Adresi',
    'book.form.treatment': 'Uygulama Seçin',
    'book.form.t1': 'Geleneksel Hamam (45 dk)',
    'book.form.t2': 'Argan Yağı Masajı (60 dk)',
    'book.form.t3': 'Çiftler için Spa Ritüeli (90 dk)',
    'book.form.t4': 'Tam Gün Sığınak Kartı',
    'book.form.submit': 'Rezervasyon Talebi Gönder',
    'book.form.or': 'Veya anında rezervasyon yapın',
    'footer.desc': 'Marakeş\'in kalbinde lüks bir sağlıklı yaşam sığınağı.',
    'footer.nav': 'Navigasyon',
    'footer.info': 'Bilgi',
    'footer.privacy': 'Gizlilik Politikası',
    'footer.terms': 'Hizmet Şartları',
    'footer.guide': 'Yerel Rehber',
    'footer.newsletter': 'Bülten',
    'footer.newsletter.desc': 'Sağlıklı yaşam ipuçları için topluluğumuza katılın.',
    'footer.rights': '© 2024 Riad Rafaele et SPA Marakeş. Tüm hakları saklıdır.'
  },
  NL: {
    'nav.about': 'Over',
    'nav.services': 'Diensten',
    'nav.gallery': 'Galerij',
    'nav.testimonials': 'Recensies',
    'nav.book': 'Nu Boeken',
    'hero.subtitle': 'De Kunst van Welzijn',
    'hero.title': 'Luxe Hammam & Spa Ervaring in de Medina van Marrakech',
    'hero.book': 'Boek uw Ervaring',
    'hero.scroll': 'Scrollen',
    'about.subtitle': 'Ons Erfgoed',
    'about.title': 'Authentieke Marokkaanse Rituelen & Sereen Toevluchtsoord',
    'about.p1': 'Bij Riad Rafaele et SPA behouden we de ziel van de Medina van Marrakech.',
    'about.p2': 'Vanaf het moment dat u onze booggangen binnenstapt, laat u de drukte achter u.',
    'services.title': 'Beste Hammam in Marrakech',
    'services.subtitle': 'Samengestelde wellnesservaringen ontworpen om lichaam en ziel te ontgiften.',
    'service1.title': 'Traditionele Hammam',
    'service1.desc': 'Een diep reinigend ritueel met zwarte zeep, kessa scrub en ghassoul klei.',
    'service2.title': 'Arganolie Massage',
    'service2.desc': 'Ervaar het vloeibare goud van Marokko met een ontspannende lichaamsmassage.',
    'service3.title': 'Koppel Ervaring',
    'service3.desc': 'Deel een moment van rust met onze zij-aan-zij behandelingen in een privésuite.',
    'services.explore': 'ONTDEK HET RITUEEL',
    'gallery.subtitle': 'Visuele Reis',
    'gallery.title': 'Het Toevluchtsoord',
    'gallery.desc': 'Elke hoek van onze Riad is ontworpen om rust te inspireren.',
    'feat1.title': 'Pure Luxe',
    'feat1.desc': 'Verfijnde ruimtes ontworpen voor de meest veeleisende reizigers.',
    'feat2.title': 'Deskundige Therapeuten',
    'feat2.desc': 'Hoog opgeleide professionals die moderne en oude technieken beheersen.',
    'feat3.title': 'Rijke Tradities',
    'feat3.desc': 'Authentieke rituelen met biologische Marokkaanse ingrediënten.',
    'feat4.title': 'Toplocatie',
    'feat4.desc': 'Een oase van rust, perfect gelegen in het hart van de historische Medina.',
    'test.subtitle': 'Stemmen van Reizigers',
    'test.quote': '"De mooiste Hammam die ik ooit heb meegemaakt. Geweldig!"',
    'test.author': '— Sarah J., Londen',
    'book.title': 'Begin Uw Reis',
    'book.desc': 'Selecteer het gewenste ritueel. Onze conciërge neemt binnenkort contact op.',
    'book.form.name': 'Volledige Naam',
    'book.form.email': 'E-mailadres',
    'book.form.treatment': 'Selecteer Behandeling',
    'book.form.t1': 'Traditionele Hammam (45 min)',
    'book.form.t2': 'Arganolie Massage (60 min)',
    'book.form.t3': 'Koppel Spa Ritueel (90 min)',
    'book.form.t4': 'Dagticket Toevluchtsoord',
    'book.form.submit': 'Boekingsaanvraag Verzenden',
    'book.form.or': 'Of boek direct via',
    'footer.desc': 'Een luxueus wellnesstoevluchtsoord in het hart van Marrakech.',
    'footer.nav': 'Navigatie',
    'footer.info': 'Informatie',
    'footer.privacy': 'Privacybeleid',
    'footer.terms': 'Servicevoorwaarden',
    'footer.guide': 'Lokale Gids',
    'footer.newsletter': 'Nieuwsbrief',
    'footer.newsletter.desc': 'Word lid van onze gemeenschap voor wellnesstips.',
    'footer.rights': '© 2024 Riad Rafaele et SPA Marrakech. Alle rechten voorbehouden.'
  }
};
